# Generated by Django 5.1.5 on 2025-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comprador', 'Comprador')], default='comprador', max_length=50, verbose_name='Tipo de Usuário'),
        ),
    ]
